version: '3.7'

services:

  database:
    image: postgres:14
    env_file:
      - .env
    networks:
      - backend

  backend:
    image: ghcr.io/captain-cap/backend:v1.0.0
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - backend

  frontend:
    image: ghcr.io/captain-cap/frontend:v1.0.0
    env_file:
      - .env
    ports:
      - 5001:5001
    networks:
      - backend

networks:
  backend:
